apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: scan-pipeline-repo
  
spec:
  params:
  - name: repo-scan

  tasks:
  - name: scan-repo
    taskRef:
      name: scan-repo
    params:
      - name: repo-scan
        value: $(params.repo-scan)
    


  
  
   
      
